include:
- project: cs/gitlabci-templates
  file: /build-image-using-kaniko.yml
- project: nse/ci
  file:
  - /ci/lib/tox-docker.yml
  - /ci/jobs/lint.yml
  - /ci/jobs/coverage.yml
  - /ci/jobs/check-packaging.yml

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 1Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 2

deploy-prod:
  stage: publish
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sonata-cell-position
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $(date +%s)-$CI_COMMIT_SHORT_SHA
    INSTALL_DEBUG_TOOLS: "true"
    KANIKO_EXTRA_ARGS:
      --build-arg PROJECT_PATH=${CI_PROJECT_PATH}
      --build-arg COMMIT_SHA=${CI_COMMIT_SHA}
      --build-arg INSTALL_DEBUG_TOOLS=${INSTALL_DEBUG_TOOLS}
  rules:
  - if: $CI_COMMIT_TAG

deploy-proxy-prod:
  stage: publish
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sonata-cell-position-proxy
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $(date +%s)-$CI_COMMIT_SHORT_SHA
    BUILD_PATH: "./proxy"
  rules:
  - if: $CI_COMMIT_TAG
