include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml
  - project: nse/ci
    file:
      - /ci/lib/tox-docker.yml
      - /ci/jobs/lint.yml


variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 1Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 2


deploy-prod:
  stage: publish
  extends: .build-image-using-kaniko
  before_script: []
  variables:
    CI_PROJECT_DIR: /builds/project/sbo/sonata-cell-position
    CI_REGISTRY_IMAGE: $CI_REGISTRY/project/sbo/sonata-cell-position
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
    KANIKO_EXTRA_ARGS:
        --build-arg PROJECT_PATH=${CI_PROJECT_PATH}
        --build-arg COMMIT_SHA=${CI_COMMIT_SHA}
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"'
    - if: '$DEPLOY == "true"'
