include:
- project: cs/gitlabci-templates
  file: /build-image-using-kaniko.yml
- project: nse/ci
  file:
  - /ci/lib/tox-docker.yml
  - /ci/jobs/lint.yml
  - /ci/jobs/coverage.yml
  - /ci/jobs/check-packaging.yml

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "schedule"  # run for scheduled pipelines
  - if: $CI_PIPELINE_SOURCE == "web"  # run for manually started pipelines from -/pipelines/new
  - if: $CI_MERGE_REQUEST_IID  # run for all the types of merge request pipelines
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # run for the default branch (not for tags)
  - if: $CI_COMMIT_TAG =~ /\d{4}\.\d+\.\d+/  # run for release tags

variables:
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  KUBERNETES_MEMORY_REQUEST: 1Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi
  KUBERNETES_CPU_REQUEST: 1
  KUBERNETES_CPU_LIMIT: 2

deploy-prod:
  stage: publish
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/sonata-cell-position
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $(date +%s)-$CI_COMMIT_SHORT_SHA
    KANIKO_EXTRA_ARGS:
      --build-arg APP_NAME=${CI_PROJECT_NAME}
      --build-arg APP_VERSION=${CI_COMMIT_TAG}
      --build-arg COMMIT_SHA=${CI_COMMIT_SHA}
  rules:
  - if: '$CI_COMMIT_TAG'

deploy-aws-prod:
  extends: deploy-prod
  variables:
    # HELP-17309
    CI_REGISTRY_IMAGE: bluebrain/obp-sonata-cell-position
    CI_REGISTRY: https://index.docker.io/v1/
    CI_REGISTRY_USER: bbpbuildbot
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD_DOCKERHUB
    REGISTRY_IMAGE_TAG: $CI_COMMIT_TAG

make-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
  - echo "Making the release for tag $CI_COMMIT_TAG"
  rules:
  - if: '$CI_COMMIT_TAG'
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
