services:
  test:
    profiles: [test]
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    command:
    - sh
    - -cx
    - |
      python -m pytest &&
      python -m coverage xml &&
      python -m coverage html
    environment:
      - APP_DEBUG=true
      - LOG_LEVEL=DEBUG
      - LOKY_EXECUTOR_ENABLED=0
      - ENTITY_CACHE_INFO=1
      - REGION_MAP_CACHE_INFO=1
      - CIRCUIT_CACHE_INFO=1
      - CACHED_SAMPLING_RATIO=0.5
      - ALTERNATIVE_REGION_MAP_CACHE_INFO=1
    volumes:
    - ./tests:/code/tests
