services:
  sonata-cell-position:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    build:
      dockerfile: Dockerfile
      args:
      - PROJECT_PATH
      - COMMIT_SHA
    ports:
    - "127.0.0.1:8200:8000"
    read_only: true
    volumes:
    - tmp:/tmp
    - type: bind
      source: /gpfs
      target: /gpfs
      read_only: true
    environment:
    - DEBUG=true
    - LOGGING_LEVEL=DEBUG

volumes:
  tmp:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=500m"
