services:
  sonata-cell-position:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    build:
      dockerfile: Dockerfile
      args:
      - APP_NAME
      - APP_VERSION
      - COMMIT_SHA
    ports:
    - "127.0.0.1:8200:8000"
    read_only: true
    volumes:
    - tmp:/tmp
    - type: bind
      source: /gpfs
      target: /gpfs
      read_only: true
    environment:
    - APP_DEBUG=true
    - PYTHONASYNCIODEBUG=1
    - LOG_LEVEL=DEBUG
    - LOG_SERIALIZE=false
    - LOG_BACKTRACE=true
    - LOG_DIAGNOSE=true
    - LOG_STANDARD_LOGGER__root=INFO
    healthcheck:
      test: [CMD, "/code/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
      start_interval: 1s
volumes:
  tmp:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=500m"
