name: Run tests

on:
    pull_request:
    push:
      branches:
        - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.22"
          enable-cache: false
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Check requirements
        run: make check-deps
      - name: Run linters
        run: make lint
      - name: Run tests
        run: make test
      - name: Cleanup
        if: ${{ always() }}
        run: |
          uv cache prune --ci
